#include "ps2emu.h"

instruction decode(u32 opcode, u32 pc) {
  auto op = opcode >> 26;
  auto rs = (opcode >> 21) & 0x1f;
  auto rt = (opcode >> 16) & 0x1f;
  auto rd = (opcode >> 11) & 0x1f;
  auto simm16 = (s16)(opcode & 0xffff);
  auto uimm16 = (u16)(opcode & 0xffff);
  auto offset = simm16 << 2 + pc + 4;
  auto code = (opcode >> 6) & 0xfffff;
  auto sa = opcode >> 6 & 0x1f;
  auto func = opcode & 0x3f;

  switch (op) {
    case 0: switch (func) {
      case 0:  return (instruction){.op=opcode, .inst=SLL, .disasm="sll %s %s %s"};
      case 1:  return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 2:  return (instruction){.op=opcode, .inst=SRL, .disasm="srl"};
      case 3:  return (instruction){.op=opcode, .inst=SRA, .disasm="sra"};
      case 4:  return (instruction){.op=opcode, .inst=SLLV, .disasm="sllv"};
      case 5:  return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 6:  return (instruction){.op=opcode, .inst=SRLV, .disasm="srlv"};
      case 7:  return (instruction){.op=opcode, .inst=SRAV, .disasm="srav"};
      case 8:  return (instruction){.op=opcode, .inst=JR, .disasm="jr"};
      case 9:  return (instruction){.op=opcode, .inst=JALR, .disasm="jalr"};
      case 10: return (instruction){.op=opcode, .inst=MOVZ, .disasm="movz"};
      case 11: return (instruction){.op=opcode, .inst=MOVN, .disasm="movn"};
      case 12: return (instruction){.op=opcode, .inst=SYSCALL, .disasm="syscall"};
      case 13: return (instruction){.op=opcode, .inst=BREAK, .disasm="break"};
      case 14: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 15: return (instruction){.op=opcode, .inst=SYNC, .disasm="sync"};
      case 16: return (instruction){.op=opcode, .inst=MFHI, .disasm="mfhi"};
      case 17: return (instruction){.op=opcode, .inst=MTHI, .disasm="mthi"};
      case 18: return (instruction){.op=opcode, .inst=MFLO, .disasm="mflo"};
      case 19: return (instruction){.op=opcode, .inst=MTLO, .disasm="mtlo"};
      case 20: return (instruction){.op=opcode, .inst=DSLLV, .disasm="dsllv"};
      case 21: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 22: return (instruction){.op=opcode, .inst=DSRLV, .disasm="dsrlv"};
      case 23: return (instruction){.op=opcode, .inst=DSRAV, .disasm="dsrav"};
      case 24: return (instruction){.op=opcode, .inst=MULT, .disasm="mult"};
      case 25: return (instruction){.op=opcode, .inst=MULTU, .disasm="multu"};
      case 26: return (instruction){.op=opcode, .inst=DIV, .disasm="div"};
      case 27: return (instruction){.op=opcode, .inst=DIVU, .disasm="divu"};
      case 28: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 29: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 30: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 31: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 32: return (instruction){.op=opcode, .inst=ADD, .disasm="add"};
      case 33: return (instruction){.op=opcode, .inst=ADDU, .disasm="addu"};
      case 34: return (instruction){.op=opcode, .inst=SUB, .disasm="sub"};
      case 35: return (instruction){.op=opcode, .inst=SUBU, .disasm="subu"};
      case 36: return (instruction){.op=opcode, .inst=AND, .disasm="and"};
      case 37: return (instruction){.op=opcode, .inst=OR, .disasm="or"};
      case 38: return (instruction){.op=opcode, .inst=XOR, .disasm="xor"};
      case 39: return (instruction){.op=opcode, .inst=NOR, .disasm="nor"};
      case 40: return (instruction){.op=opcode, .inst=MFSA, .disasm="mfsa"};
      case 41: return (instruction){.op=opcode, .inst=MTSA, .disasm="mtsa"};
      case 42: return (instruction){.op=opcode, .inst=SLT, .disasm="slt"};
      case 43: return (instruction){.op=opcode, .inst=SLTU, .disasm="sltu"};
      case 44: return (instruction){.op=opcode, .inst=DADD, .disasm="dadd"};
      case 45: return (instruction){.op=opcode, .inst=DADDU, .disasm="daddu"};
      case 46: return (instruction){.op=opcode, .inst=DSUB, .disasm="dsub"};
      case 47: return (instruction){.op=opcode, .inst=DSUBU, .disasm="dsubu"};
      case 48: return (instruction){.op=opcode, .inst=TGE, .disasm="tge"};
      case 49: return (instruction){.op=opcode, .inst=TGEU, .disasm="tgeu"};
      case 50: return (instruction){.op=opcode, .inst=TLT, .disasm="tlt"};
      case 51: return (instruction){.op=opcode, .inst=TLTU, .disasm="tltu"};
      case 52: return (instruction){.op=opcode, .inst=TEQ, .disasm="teq"};
      case 53: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 54: return (instruction){.op=opcode, .inst=TNE, .disasm="tne"};
      case 55: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 56: return (instruction){.op=opcode, .inst=DSLL, .disasm="dsll"};
      case 57: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 58: return (instruction){.op=opcode, .inst=DSRL, .disasm="dsrl"};
      case 59: return (instruction){.op=opcode, .inst=DSRA, .disasm="dsra"};
      case 60: return (instruction){.op=opcode, .inst=DSLL32, .disasm="dsll32"};
      case 61: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 62: return (instruction){.op=opcode, .inst=DSRL32, .disasm="dsrl32"};
      case 63: return (instruction){.op=opcode, .inst=DSRA32, .disasm="dsra32"};
      default: return (instruction){.op=opcode, .inst=INVALID, .disasm="bltz"};
    } break;
    case 1: switch (rt) {
      case 0:  return (instruction){.op=opcode, .inst=BLTZ, .disasm="bltz"};
      case 1:  return (instruction){.op=opcode, .inst=BGEZ, .disasm="bgez"};
      case 2:  return (instruction){.op=opcode, .inst=BLTZL, .disasm="bltzl"};
      case 3:  return (instruction){.op=opcode, .inst=BGEZL, .disasm="bgezl"};
      case 4:  return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 5:  return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 6:  return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 7:  return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 8:  return (instruction){.op=opcode, .inst=TGEI, .disasm="tgei"};
      case 9:  return (instruction){.op=opcode, .inst=TGEIU, .disasm="tgeiu"};
      case 10: return (instruction){.op=opcode, .inst=TLTI, .disasm="tlti"};
      case 11: return (instruction){.op=opcode, .inst=TLTIU, .disasm="tltiu"};
      case 12: return (instruction){.op=opcode, .inst=TEQI, .disasm="teqi"};
      case 13: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 14: return (instruction){.op=opcode, .inst=TNEI, .disasm="tnei"};
      case 15: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 16: return (instruction){.op=opcode, .inst=BLTZAL, .disasm="bltzal"};
      case 17: return (instruction){.op=opcode, .inst=BGEZAL, .disasm="bgezal"};
      case 18: return (instruction){.op=opcode, .inst=BLTZALL, .disasm="bltzall"};
      case 19: return (instruction){.op=opcode, .inst=BGEZALL, .disasm="bgezall"};
      case 20: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 21: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 22: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 23: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 24: return (instruction){.op=opcode, .inst=MTSAB, .disasm="mtsab"};
      case 25: return (instruction){.op=opcode, .inst=MTSAH, .disasm="mstah"};
      case 26: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 27: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 28: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 29: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 30: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      case 31: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
      default: return (instruction){.op=opcode, .inst=INVALID, .disasm="bltz"};
    } break;
    case 2:  return (instruction){.op=opcode, .inst=J, .disasm="j"};
    case 3:  return (instruction){.op=opcode, .inst=JAL, .disasm="jal"};
    case 4:  return (instruction){.op=opcode, .inst=BEQ, .disasm="beq"};
    case 5:  return (instruction){.op=opcode, .inst=BNE, .disasm="bne"};
    case 6:  return (instruction){.op=opcode, .inst=BLEZ, .disasm="blez"};
    case 7:  return (instruction){.op=opcode, .inst=BGTZ, .disasm="bgtz"};
    case 8:  return (instruction){.op=opcode, .inst=ADDI, .disasm="addi"};
    case 9:  return (instruction){.op=opcode, .inst=ADDIU, .disasm="addiu"};
    case 10: return (instruction){.op=opcode, .inst=SLTI, .disasm="slti"};
    case 11: return (instruction){.op=opcode, .inst=SLTIU, .disasm="sltiu"};
    case 12: return (instruction){.op=opcode, .inst=ANDI, .disasm="andi"};
    case 13: return (instruction){.op=opcode, .inst=ORI, .disasm="ori"};
    case 14: return (instruction){.op=opcode, .inst=XORI, .disasm="xori"};
    case 15: return (instruction){.op=opcode, .inst=LUI, .disasm="lui"};
    case 16: switch (rs) {
      //case 0: switch () TODO: breakpoint stuff
      //case 4: switch () TODO: breakpoint stuff
      case 8: switch (rt) {
        case 0: return (instruction){.op=opcode, .inst=BC0F, .disasm="lui"};
        case 1: return (instruction){.op=opcode, .inst=BC0T, .disasm="lui"};
        case 2: return (instruction){.op=opcode, .inst=BC0FL, .disasm="lui"};
        case 3: return (instruction){.op=opcode, .inst=BC0TL, .disasm="lui"};
        default: return (instruction){.op=opcode, .inst=INVALID, .disasm="bltz"};
      } break;
      case 16: switch (func) {
        case 1: return (instruction){.op=opcode, .inst=TLBR, .disasm="lui"};
        case 2: return (instruction){.op=opcode, .inst=TLBWI, .disasm="lui"};
        case 6: return (instruction){.op=opcode, .inst=TLBWR, .disasm="lui"};
        case 8: return (instruction){.op=opcode, .inst=TLBP, .disasm="lui"};
        case 16: return (instruction){.op=opcode, .inst=ERET, .disasm="lui"};
        case 56: return (instruction){.op=opcode, .inst=EI, .disasm="lui"};
        case 57: return (instruction){.op=opcode, .inst=DI, .disasm="lui"};
        default: return (instruction){.op=opcode, .inst=INVALID, .disasm="lui"};
      }
      default: return (instruction){.op=opcode, .inst=INVALID, .disasm="lui"};
    }
    case 17: switch (rs) {
      case 0: return (instruction){.op=opcode, .inst=MFC1, .disasm="lui"};
      case 2: return (instruction){.op=opcode, .inst=CFC1, .disasm="lui"};
      case 4: return (instruction){.op=opcode, .inst=MTC1, .disasm="lui"};
      case 6: return (instruction){.op=opcode, .inst=CTC1, .disasm="lui"};
      case 8: switch (rt) {
        case 0: return (instruction){.op=opcode, .inst=BC1F, .disasm="lui"};
        case 1: return (instruction){.op=opcode, .inst=BC1T, .disasm="lui"};
        case 2: return (instruction){.op=opcode, .inst=BC1FL, .disasm="lui"};
        case 3: return (instruction){.op=opcode, .inst=BC1TL, .disasm="lui"};
        default: return (instruction){.op=opcode, .inst=INVALID, .disasm="lui"};
      } break;
      case 16: switch (func) {

      }

    }
    case 18: // COP2
    case 19: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
    case 20: return (instruction){.op=opcode, .inst=BEQL, .disasm="beql"};
    case 21: return (instruction){.op=opcode, .inst=BNEL, .disasm="bnel"};
    case 22: return (instruction){.op=opcode, .inst=BLEZL, .disasm="blezl"};
    case 23: return (instruction){.op=opcode, .inst=BGTZL, .disasm="bgtzl"};
    case 24: return (instruction){.op=opcode, .inst=DADDI, .disasm="daddi"};
    case 25: return (instruction){.op=opcode, .inst=DADDIU, .disasm="daddiu"};
    case 26: return (instruction){.op=opcode, .inst=LDL, .disasm="ldl"};
    case 27: return (instruction){.op=opcode, .inst=LDR, .disasm="LDR"};
    case 28: switch (func) {
      case 0:  return (instruction){.op=opcode, .inst=MADD, .disasm="sll %s %s %s"};
      case 1:  return (instruction){.op=opcode, .inst=MADDU, .disasm="invalid"};
      case 4:  return (instruction){.op=opcode, .inst=PLZCW, .disasm="invalid"};
      case 8:  switch (sa) {
        case 0:  return (instruction){.op=opcode, .inst=PADDW, .disasm="bltz"};
        case 1:  return (instruction){.op=opcode, .inst=PSUBW, .disasm="bgez"};
        case 2:  return (instruction){.op=opcode, .inst=PCGTW, .disasm="bltzl"};
        case 3:  return (instruction){.op=opcode, .inst=PMAXW, .disasm="bgezl"};
        case 4:  return (instruction){.op=opcode, .inst=PADDH, .disasm="invalid"};
        case 5:  return (instruction){.op=opcode, .inst=PSUBH, .disasm="invalid"};
        case 6:  return (instruction){.op=opcode, .inst=PCGTH, .disasm="invalid"};
        case 7:  return (instruction){.op=opcode, .inst=PMAXH, .disasm="invalid"};
        case 8:  return (instruction){.op=opcode, .inst=PADDB, .disasm="tgei"};
        case 9:  return (instruction){.op=opcode, .inst=PSUBB, .disasm="tgeiu"};
        case 10: return (instruction){.op=opcode, .inst=PCGTB, .disasm="tlti"};
        case 11: return (instruction){.op=opcode, .inst=INVALID, .disasm="tltiu"};
        case 12: return (instruction){.op=opcode, .inst=INVALID, .disasm="teqi"};
        case 13: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
        case 14: return (instruction){.op=opcode, .inst=INVALID, .disasm="tnei"};
        case 15: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
        case 16: return (instruction){.op=opcode, .inst=PADDSW, .disasm="bltzal"};
        case 17: return (instruction){.op=opcode, .inst=PSUBSW, .disasm="bgezal"};
        case 18: return (instruction){.op=opcode, .inst=PEXTLW, .disasm="bltzall"};
        case 19: return (instruction){.op=opcode, .inst=PPACW, .disasm="bgezall"};
        case 20: return (instruction){.op=opcode, .inst=PADDSH, .disasm="invalid"};
        case 21: return (instruction){.op=opcode, .inst=PSUBSH, .disasm="invalid"};
        case 22: return (instruction){.op=opcode, .inst=PEXTLH, .disasm="invalid"};
        case 23: return (instruction){.op=opcode, .inst=PPACH, .disasm="invalid"};
        case 24: return (instruction){.op=opcode, .inst=PADDSB, .disasm="mtsab"};
        case 25: return (instruction){.op=opcode, .inst=PSUBSB, .disasm="mstah"};
        case 26: return (instruction){.op=opcode, .inst=PEXTLB, .disasm="invalid"};
        case 27: return (instruction){.op=opcode, .inst=PPACB, .disasm="invalid"};
        case 28: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
        case 29: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
        case 30: return (instruction){.op=opcode, .inst=PEXT5, .disasm="invalid"};
        case 31: return (instruction){.op=opcode, .inst=PPAC5, .disasm="invalid"};
        default: return (instruction){.op=opcode, .inst=INVALID, .disasm="bltz"};
      } break;
      case 9:  switch (sa) {
        case 0:  return (instruction){.op=opcode, .inst=PMADDW, .disasm="bltz"};
        case 1:  return (instruction){.op=opcode, .inst=INVALID, .disasm="bgez"};
        case 2:  return (instruction){.op=opcode, .inst=PSLLVW, .disasm="bltzl"};
        case 3:  return (instruction){.op=opcode, .inst=PSRLVW, .disasm="bgezl"};
        case 4:  return (instruction){.op=opcode, .inst=PMSUBW, .disasm="invalid"};
        case 5:  return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
        case 6:  return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
        case 7:  return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
        case 8:  return (instruction){.op=opcode, .inst=PMFHI, .disasm="tgei"};
        case 9:  return (instruction){.op=opcode, .inst=PMFLO, .disasm="tgeiu"};
        case 10: return (instruction){.op=opcode, .inst=PINTH, .disasm="tlti"};
        case 11: return (instruction){.op=opcode, .inst=INVALID, .disasm="tltiu"};
        case 12: return (instruction){.op=opcode, .inst=PMULTW, .disasm="teqi"};
        case 13: return (instruction){.op=opcode, .inst=PDIVW, .disasm="invalid"};
        case 14: return (instruction){.op=opcode, .inst=PCPYLD, .disasm="tnei"};
        case 15: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
        case 16: return (instruction){.op=opcode, .inst=PMADDH, .disasm="bltzal"};
        case 17: return (instruction){.op=opcode, .inst=PHMADH, .disasm="bgezal"};
        case 18: return (instruction){.op=opcode, .inst=PAND, .disasm="bltzall"};
        case 19: return (instruction){.op=opcode, .inst=PXOR, .disasm="bgezall"};
        case 20: return (instruction){.op=opcode, .inst=PMSUBH, .disasm="invalid"};
        case 21: return (instruction){.op=opcode, .inst=PHMSBH, .disasm="invalid"};
        case 22: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
        case 23: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
        case 24: return (instruction){.op=opcode, .inst=INVALID, .disasm="mtsab"};
        case 25: return (instruction){.op=opcode, .inst=INVALID, .disasm="mstah"};
        case 26: return (instruction){.op=opcode, .inst=PEXEH, .disasm="invalid"};
        case 27: return (instruction){.op=opcode, .inst=PREVH, .disasm="invalid"};
        case 28: return (instruction){.op=opcode, .inst=PMULTH, .disasm="invalid"};
        case 29: return (instruction){.op=opcode, .inst=PDIVBW, .disasm="invalid"};
        case 30: return (instruction){.op=opcode, .inst=PEXEH, .disasm="invalid"};
        case 31: return (instruction){.op=opcode, .inst=PROT3W, .disasm="invalid"};
        default: return (instruction){.op=opcode, .inst=INVALID, .disasm="bltz"};
      } break;
      case 16: return (instruction){.op=opcode, .inst=MFHI1, .disasm="sll %s %s %s"};
      case 17: return (instruction){.op=opcode, .inst=MTHI1, .disasm="sll %s %s %s"};
      case 18: return (instruction){.op=opcode, .inst=MFLO1, .disasm="sll %s %s %s"};
      case 19: return (instruction){.op=opcode, .inst=MTLO1, .disasm="sll %s %s %s"};
      case 24: return (instruction){.op=opcode, .inst=MULT1, .disasm="sll %s %s %s"};
      case 25: return (instruction){.op=opcode, .inst=MULTU1, .disasm="sll %s %s %s"};
      case 26: return (instruction){.op=opcode, .inst=DIV1, .disasm="sll %s %s %s"};
      case 27: return (instruction){.op=opcode, .inst=DIVU1, .disasm="sll %s %s %s"};
      case 32: return (instruction){.op=opcode, .inst=MADD1, .disasm="sll %s %s %s"};
      case 33: return (instruction){.op=opcode, .inst=MADDU1, .disasm="sll %s %s %s"};
      case 40:  switch (sa) {
        case 0:  return (instruction){.op=opcode, .inst=INVALID, .disasm="bltz"};
        case 1:  return (instruction){.op=opcode, .inst=PABSW, .disasm="bgez"};
        case 2:  return (instruction){.op=opcode, .inst=PCEQW, .disasm="bltzl"};
        case 3:  return (instruction){.op=opcode, .inst=PMINW, .disasm="bgezl"};
        case 4:  return (instruction){.op=opcode, .inst=PADSBH, .disasm="invalid"};
        case 5:  return (instruction){.op=opcode, .inst=PABSH, .disasm="invalid"};
        case 6:  return (instruction){.op=opcode, .inst=PCEQH, .disasm="invalid"};
        case 7:  return (instruction){.op=opcode, .inst=PMINH, .disasm="invalid"};
        case 8:  return (instruction){.op=opcode, .inst=INVALID, .disasm="tgei"};
        case 9:  return (instruction){.op=opcode, .inst=INVALID, .disasm="tgeiu"};
        case 10: return (instruction){.op=opcode, .inst=PCEQB, .disasm="tlti"};
        case 11: return (instruction){.op=opcode, .inst=INVALID, .disasm="tltiu"};
        case 12: return (instruction){.op=opcode, .inst=INVALID, .disasm="teqi"};
        case 13: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
        case 14: return (instruction){.op=opcode, .inst=INVALID, .disasm="tnei"};
        case 15: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
        case 16: return (instruction){.op=opcode, .inst=PADDUW, .disasm="bltzal"};
        case 17: return (instruction){.op=opcode, .inst=PSUBUW, .disasm="bgezal"};
        case 18: return (instruction){.op=opcode, .inst=PEXTUW, .disasm="bltzall"};
        case 19: return (instruction){.op=opcode, .inst=INVALID, .disasm="bgezall"};
        case 20: return (instruction){.op=opcode, .inst=PADDUH, .disasm="invalid"};
        case 21: return (instruction){.op=opcode, .inst=PSUBUH, .disasm="invalid"};
        case 22: return (instruction){.op=opcode, .inst=PEXTUH, .disasm="invalid"};
        case 23: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
        case 24: return (instruction){.op=opcode, .inst=PADDUB, .disasm="mtsab"};
        case 25: return (instruction){.op=opcode, .inst=PSUBUB, .disasm="mstah"};
        case 26: return (instruction){.op=opcode, .inst=PEXTUB, .disasm="invalid"};
        case 27: return (instruction){.op=opcode, .inst=QFSRV, .disasm="invalid"};
        case 28: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
        case 29: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
        case 30: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
        case 31: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
        default: return (instruction){.op=opcode, .inst=INVALID, .disasm="bltz"};
      } break;
      case 41:  switch (sa) {
        case 0:  return (instruction){.op=opcode, .inst=PMADDUW, .disasm="bltz"};
        case 3:  return (instruction){.op=opcode, .inst=PSRAVW, .disasm="bltz"};
        case 8:  return (instruction){.op=opcode, .inst=PMTHI, .disasm="bltz"};
        case 9:  return (instruction){.op=opcode, .inst=PMTLO, .disasm="bltz"};
        case 10: return (instruction){.op=opcode, .inst=PINTEH, .disasm="bltz"};
        case 12: return (instruction){.op=opcode, .inst=PMULTUW, .disasm="bltz"};
        case 13: return (instruction){.op=opcode, .inst=PDIVUW, .disasm="bltz"};
        case 14: return (instruction){.op=opcode, .inst=PCPYUD, .disasm="bltz"};
        case 18: return (instruction){.op=opcode, .inst=POR, .disasm="bltz"};
        case 19: return (instruction){.op=opcode, .inst=PNOR, .disasm="bltz"};
        case 26: return (instruction){.op=opcode, .inst=PEXCH, .disasm="bltz"};
        case 27: return (instruction){.op=opcode, .inst=PCPYH, .disasm="bltz"};
        case 30: return (instruction){.op=opcode, .inst=PEXCW, .disasm="bltz"};
        default: return (instruction){.op=opcode, .inst=INVALID, .disasm="bltz"};
      } break;
      case 48: return (instruction){.op=opcode, .inst=PMFHL, .disasm="sll %s %s %s"};
      case 49: return (instruction){.op=opcode, .inst=PMTHL, .disasm="sll %s %s %s"};
      case 52: return (instruction){.op=opcode, .inst=PSLLH, .disasm="sll %s %s %s"};
      case 54: return (instruction){.op=opcode, .inst=PSRLH, .disasm="sll %s %s %s"};
      case 55: return (instruction){.op=opcode, .inst=PSRAH, .disasm="sll %s %s %s"};
      case 60: return (instruction){.op=opcode, .inst=PSLLW, .disasm="sll %s %s %s"};
      case 62: return (instruction){.op=opcode, .inst=PSRLW, .disasm="sll %s %s %s"};
      case 63: return (instruction){.op=opcode, .inst=PSRAW, .disasm="sll %s %s %s"};
      default: return (instruction){.op=opcode, .inst=INVALID, .disasm="sll %s %s %s"};
    }
    case 29: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
    case 30: return (instruction){.op=opcode, .inst=LQ, .disasm="lq"};
    case 31: return (instruction){.op=opcode, .inst=SQ, .disasm="sq"};
    case 32: return (instruction){.op=opcode, .inst=LB, .disasm="lb"};
    case 33: return (instruction){.op=opcode, .inst=LH, .disasm="lh"};
    case 34: return (instruction){.op=opcode, .inst=LWL, .disasm="lwl"};
    case 35: return (instruction){.op=opcode, .inst=LW, .disasm="lw"};
    case 36: return (instruction){.op=opcode, .inst=LBU, .disasm="lbu"};
    case 37: return (instruction){.op=opcode, .inst=LHU, .disasm="lhu"};
    case 38: return (instruction){.op=opcode, .inst=LWR, .disasm="lwr"};
    case 39: return (instruction){.op=opcode, .inst=LWU, .disasm="lwu"};
    case 40: return (instruction){.op=opcode, .inst=SB, .disasm="sb"};
    case 41: return (instruction){.op=opcode, .inst=SH, .disasm="sh"};
    case 42: return (instruction){.op=opcode, .inst=SWL, .disasm="swl"};
    case 43: return (instruction){.op=opcode, .inst=SW, .disasm="sw"};
    case 44: return (instruction){.op=opcode, .inst=SDL, .disasm="sdl"};
    case 45: return (instruction){.op=opcode, .inst=SDR, .disasm="sdr"};
    case 46: return (instruction){.op=opcode, .inst=SWR, .disasm="dsub"};
    case 47: return (instruction){.op=opcode, .inst=CACHE, .disasm="cache"};
    case 48: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
    case 49: return (instruction){.op=opcode, .inst=LWC1, .disasm="lwc1"};
    case 50: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
    case 51: return (instruction){.op=opcode, .inst=PREF, .disasm="pref"};
    case 52: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
    case 53: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
    case 54: return (instruction){.op=opcode, .inst=LQC2, .disasm="lqc2"};
    case 55: return (instruction){.op=opcode, .inst=LD, .disasm="ld"};
    case 56: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
    case 57: return (instruction){.op=opcode, .inst=SWC1, .disasm="swc1"};
    case 58: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
    case 59: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
    case 60: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
    case 61: return (instruction){.op=opcode, .inst=INVALID, .disasm="invalid"};
    case 62: return (instruction){.op=opcode, .inst=SQC2, .disasm="sqc2"};
    case 63: return (instruction){.op=opcode, .inst=SD, .disasm="SD"};
  }
}

void execute(ps2* ps2, mips* mips, instruction instruction) {
  switch (instruction.inst) {
  case INVALID: break;
  case LB: break;
  case LBU: break;
  case LD: break;
  case LDL: break;
  case LDR: break;
  case LH: break;
  case LHU: break;
  case LW: break;
  case LWL: break;
  case LWR: break;
  case LWU: break;
  case SB: break;
  case SD: break;
  case SDL: break;
  case SDR: break;
  case SH: break;
  case SW: break;
  case SWL: break;
  case SWR: break;
  case ADDI: break;
  case ADDIU: break;
  case ANDI: break;
  case DADDI: break;
  case DADDIU: break;
  case LUI: break;
  case ORI: break;
  case SLTI: break;
  case SLTIU: break;
  case XORI: break;
  case ADD: break;
  case ADDU: break;
  case AND: break;
  case DADD: break;
  case DADDU: break;
  case DSUB: break;
  case DSUBU: break;
  case NOR: break;
  case OR: break;
  case SLT: break;
  case SLTU: break;
  case SUB: break;
  case SUBU: break;
  case XOR: break;
  case DSLL: break;
  case DSLL32: break;
  case DSLLV: break;
  case DSRA: break;
  case DSRA32: break;
  case DSRAV: break;
  case DSRL: break;
  case DSRL32: break;
  case DSRLV: break;
  case SLL: break;
  case SLLV: break;
  case SRA: break;
  case SRAV: break;
  case SRL: break;
  case SRLV: break;
  case DIV: break;
  case DIVU: break;
  case MFHI: break;
  case MFLO: break;
  case MTHI: break;
  case MTLO: break;
  case MULT: break;
  case MULTU: break;
  case J: break;
  case JAL: break;
  case JALR: break;
  case JR: break;
  case BEQ: break;
  case BEQL: break;
  case BGEZ: break;
  case BGEZAL: break;
  case BGEZALL: break;
  case BGEZL: break;
  case BGTZ: break;
  case BGTZL: break;
  case BLEZ: break;
  case BLEZL: break;
  case BLTZ: break;
  case BLTZAL: break;
  case BLTZALL: break;
  case BLTZL: break;
  case BNE: break;
  case BNEL: break;
  case SYSCALL: break;
  case BREAK: break;
  case TGE: break;
  case TGEU: break;
  case TLT: break;
  case TLTU: break;
  case TEQ: break;
  case TNE: break;
  case TGEI: break;
  case TGEIU: break;
  case TLTI: break;
  case TLTIU: break;
  case TEQI: break;
  case TNEI: break;
  case SYNC: break;
  case MOVN: break;
  case MOVZ: break;
  case PREF: break;
  case MADD: break;
  case MADDU: break;
  case MULT1: break;
  case MULTU1: break;
  case DIV1: break;
  case DIVU1: break;
  case MADD1: break;
  case MADDU1: break;
  case MFHI1: break;
  case MTHI1: break;
  case MFLO1: break;
  case MTLO1: break;
  case PADDB: break;
  case PSUBB: break;
  case PADDH: break;
  case PSUBH: break;
  case PADDW: break;
  case PSUBW: break;
  case PADSBH: break;
  case PADDSB: break;
  case PSUBSB: break;
  case PADDSH: break;
  case PSUBSH: break;
  case PADDSW: break;
  case PSUBSW: break;
  case PADDUB: break;
  case PSUBUB: break;
  case PADDUH: break;
  case PSUBUH: break;
  case PADDUW: break;
  case PSUBUW: break;
  case PMULTW: break;
  case PMULTUW: break;
  case PDIVW: break;
  case PDIVUW: break;
  case PMADDW: break;
  case PMADDUW: break;
  case PMSUBW: break;
  case PMFHI: break;
  case PMTHI: break;
  case PMFLO: break;
  case PMTLO: break;
  case PMULTH: break;
  case PMADDH: break;
  case PMSUBH: break;
  case PMFHL: break;
  case PMTHL: break;
  case PHMADH: break;
  case PHMSBH: break;
  case PDIVBW: break;
  case MFSA: break;
  case MTSA: break;
  case MTSAB: break;
  case MTSAH: break;
  case PSLLH: break;
  case PSRLH: break;
  case PSRAH: break;
  case PSLLW: break;
  case PSLLVW: break;
  case PSRLW: break;
  case PSRLVW: break;
  case PSRAW: break;
  case PSRAVW: break;
  case QFSRV: break;
  case PABSH: break;
  case PABSW: break;
  case PMAXH: break;
  case PMINH: break;
  case PMAXW: break;
  case PMINW: break;
  case PAND: break;
  case POR: break;
  case PNOR: break;
  case PXOR: break;
  case PCGTB: break;
  case PCEQB: break;
  case PCGTH: break;
  case PCEQH: break;
  case PCGTW: break;
  case PCEQW: break;
  case PLZCW: break;
  case LQ: break;
  case SQ: break;
  case PPACB: break;
  case PPACH: break;
  case PINTEH: break;
  case PPACW: break;
  case PEXTUB: break;
  case PEXTLB: break;
  case PEXTUH: break;
  case PEXTLH: break;
  case PEXTUW: break;
  case PEXTLW: break;
  case PEXT5: break;
  case PPAC5: break;
  case PCPYH: break;
  case PCPYLD: break;
  case PCPYUD: break;
  case PREVH: break;
  case PINTH: break;
  case PEXEH: break;
  case PEXCH: break;
  case PEXEW: break;
  case PEXCW: break;
  case PROT3W: break;
  case BC0F: break;
  case BC0FL: break;
  case BC0T: break;
  case BC0TL: break;
  case CACHE: break;
  case DI: break;
  case EI: break;
  case ERET: break;
  case MFC0: break;
  case MTC0: break;
  case TLBR: break;
  case TLBWI: break;
  case TLBWR: break;
  case TLBP: break;
  case LWC1: break;
  case SWC1: break;
  case MTC1: break;
  case MFC1: break;
  case MOV_S: break;
  case CTC1: break;
  case CFC1: break;
  case CVT_S_W: break;
  case CVT_W_S: break;
  case ADD_S: break;
  case SUB_S: break;
  case MUL_S: break;
  case DIV_S: break;
  case ABS_S: break;
  case NEG_S: break;
  case SQRT_S: break;
  case ADDA_S: break;
  case SUBA_S: break;
  case MULA_S: break;
  case MADD_S: break;
  case MADDA_S: break;
  case MSUB_S: break;
  case MSUBA_S: break;
  case RSQRT_S: break;
  case MAX_S: break;
  case MIN_S: break;
  case C_LS_S: break;
  //TODO: and the like
  case BC1T: break;
  case BC1F: break;
  case BC1TL: break;
  case BC1FL: break;
  case BC2F: break;
  case BC2FL: break;
  case BC2T: break;
  case BC2TL: break;
  case CALLMS: break;
  case CALLMSR: break;
  case CFC2: break;
  case CTC2: break;
  case LQC2: break;
  case SQC2: break;
  case QMFC2: break;
  case QMTC2: break;
  case WAITQ: break;
  }
}


int main(int argc, char** argv) {
  auto ptr = malloc(1234);
  free(ptr);
  auto asdf = 1;
  printf("hello world\n");
  return 0;
}